"""Simple table reconstruction with safe wrapping and pagination."""

from .models import (
    CellAlignment,
    SimpleTable,
    TableCell,
    TableError,
    TableLayoutCell,
    TableLayoutRow,
    TablePage,
    TableReconstructionResult,
    TableRect,
    TableRow,
    TableStructureError,
    TableValidation,
    TableWarning,
    TableWarningCode,
    TableWarningSeverity,
    numeric_signature,
)
from .reconstructor import (
    SimpleTableReconstructor,
    TableLayoutSettings,
    TableReconstructor,
    reconstruct_simple_table,
    render_table_html,
)

__all__ = [
    "CellAlignment",
    "SimpleTable",
    "SimpleTableReconstructor",
    "TableCell",
    "TableError",
    "TableLayoutCell",
    "TableLayoutRow",
    "TableLayoutSettings",
    "TablePage",
    "TableRect",
    "TableReconstructionResult",
    "TableReconstructor",
    "TableRow",
    "TableStructureError",
    "TableValidation",
    "TableWarning",
    "TableWarningCode",
    "TableWarningSeverity",
    "numeric_signature",
    "reconstruct_simple_table",
    "render_table_html",
]
