"""Safe preservation of extracted images during reconstruction."""

from .preservation import (
    CaptionPlacement,
    CaptionRelation,
    CaptionSpec,
    FitMode,
    ImageAsset,
    ImageFit,
    ImagePlacement,
    ImagePosition,
    ImagePreservationError,
    ImagePreservationMetric,
    ImagePreserver,
    ImageRect,
    ImageWarning,
    ImageWarningCode,
    MissingImageError,
    PlacementPosition,
    PreservedImage,
    RenderedImage,
    preserve_image,
    render_preserved_image,
)

__all__ = [
    "CaptionPlacement",
    "CaptionRelation",
    "CaptionSpec",
    "FitMode",
    "ImageAsset",
    "ImageFit",
    "ImagePlacement",
    "ImagePosition",
    "ImagePreservationError",
    "ImagePreservationMetric",
    "ImagePreserver",
    "ImageRect",
    "ImageWarning",
    "ImageWarningCode",
    "MissingImageError",
    "PlacementPosition",
    "PreservedImage",
    "RenderedImage",
    "preserve_image",
    "render_preserved_image",
]
